/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "AGCCloudDBObjectTypeHeaders.h"

static const long ObjectTypeVersion = 15;

static const int FormatVersion = 1;

@implementation AGCCloudDBObjectTypeInfoHelper

+ (AGCCloudDBObjectTypeInfo *)obtainObjectTypeInfo {
    return [[AGCCloudDBObjectTypeInfo alloc] initWithObjectTypes:@[UserFeedback.class,
                                                                   UserInfo.class,
                                                                   UserPoint.class,
                                                                   UserPointLog.class,
                                                                   UserUsageLog.class]
                                               objectTypeVersion:ObjectTypeVersion
                                                   formatVersion:FormatVersion];
}

@end
