/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "UserPoint.h"

@implementation UserPoint

+ (NSArray<NSString *> *)primaryKeyProperties {
    return @[@"userId"];
}

+ (NSArray<NSString *> *)notNullProperties {
    return @[@"userId"];
}

@end
